version: '2'

services:
    hrci_back:
        image: hrci_back
        ports:
            - "5000:5000"
        volumes:
            - ./:/code
        restart: always
        networks:
            - backend-network
networks:
    backend-network:
        driver: bridge
