version: '3'

services:
    hrci:
        image: hrci
        ports:
            - "5000:5000"
        restart: always
        networks:
            - code-network-dev
networks:
    code-network-dev:
        driver: bridge
