
version: '2'

services:
    hrci_back:
        image: hrci_back
        ports:
            - "5000:5000"
        environment:
            - ISENV=pro
        volumes:
            - ./:/code
            - uploads:/app/uploads"
            - Template:/app/Template
        restart: always
        networks:
            - backend-network
networks:
    backend-network:
        driver: bridge
volumes:
    uploads:
        external: True
