
version: '2'

services:
    hrci_back:
        image: hrci_back
        ports:
            - "8888:8888"
        environment:
            - ISENV=pro
        volumes:
            - ./:/code
            - "/home/ubuntu/state/HRCI/uploads:/app/uploads"
            - "/home/ubuntu/state/HRCI/Template:/app/Template"
        restart: always
        networks:
            - backend-network-state
networks:
    backend-network-state:
        driver: bridge
