version: '3'

services:
    server_test:
        image: server_test
        ports:
            - "5000:5000"
        restart: always
        networks:
            - code-network-dev
networks:
    code-network-dev:
        driver: bridge
