
version: '2'

services:
    hrci_state:
        image: hrci_state
        ports:
            - "8888:8888"
        environment:
            - ISENV=pro
        volumes:
            - ./:/code
            - "/home/ubuntu/pro/HRCI/uploads:/app/uploads"
            - "/home/ubuntu/pro/HRCI/Template:/app/Template"
        restart: always
        networks:
            - backend-network
networks:
    backend-network:
        driver: bridge
