version: '2'

services:
    hrci_state:
        image: hrci_state
        ports:
            - "5000:5000"
        environment:
            - ISENV=dev
        volumes:
            - ./:/code
            - "/home/ubuntu/dev/HRCI/uploads:/app/uploads"
            - "/home/ubuntu/dev/HRCI/Template:/app/Template"
        restart: always
        networks:
            - code-network-dev
networks:
    code-network-dev:
        driver: bridge
