version: '2'

services:
    hrci_back_dev:
        image: hrci_back_dev
        ports:
            - "3000:5000"
        environment:
            - ISENV=dev
        volumes:
            - ./:/code
            - "/home/ubuntu/pro/HRCI/uploads:/app/uploads"
            - "/home/ubuntu/pro/HRCI/Template:/app/Template"
        restart: always
        networks:
            - code-network-dev
networks:
    code-network-dev:
        driver: bridge
